GENERAL:
  tag: xtrans_scanrefer
  model: xtrans
  dataset: ScanRefer
  dataloader: dataset
  detection: False
  use_gt_ins: True
  mode: gt
  use_tf: True
  num_proposals: 64
  use_rl: False

DATA:
  use_color: True
  num_points: 40000

TRAIN:
  batch_size: 32
  epoch: 25
  use_pretrain: False
  lr: 0.0001
